repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.3.5'
    hooks:
    -   id: ruff
        files: 'QWeb'
    -   id: ruff-format
        files: 'QWeb'

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0'
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --disable-error-code=import-untyped]
        files: 'QWeb'
